version: '2'
services:
  mariadb:
    image: mariadb:latest
    environment:
      MYSQL_ROOT_PASSWORD: qVdj1G9y90y2
      MYSQL_USER: dbu_{summary}
      MYSQL_DATABASE: dbo_{summary}
      MYSQL_PASSWORD: lnM6G86ou6i2
    stdin_open: true
    volumes:
    - customer_{summary}:/var/lib/mysql
    tty: true
    labels:
      io.rancher.container.pull_image: always
  loadbalancer:
    image: rancher/lb-service-haproxy:v0.9.6
    expose:
    - 80:80/tcp
    labels:
      io.rancher.container.agent.role: environmentAdmin,agent
      io.rancher.container.agent_service.drain_provider: 'true'
      io.rancher.container.create_agent: 'true'
      web.http: 'true'
  prestashop:
    image: hkosbab/prestashop
    stdin_open: true
    volumes:
    - customer_{summary}_data:/var/www/html
    tty: true
    links:
    - mariadb:db
    labels:
      io.rancher.container.pull_image: always
