version: '2'
catalog:
  name: 'Prestashop'
  version: '1.6.1.18'# Version of the versioned template of the Catalog Entry
  description: # Description of the versioned template of the Catalog Entry
  uuid: 'prestashop-1'# Unique identifier to be used for upgrades. Please see note.
  minimum_rancher_version: v0.51.0 # The minimum version of Rancher that supports the template
  questions: #Used to request user input for configuration options
   - variable: Domain
      description: "public port to access the drupal site"
      label: "Domain"
      required: true
      default: "example.com"
      type: "string"
  - variable: summary
      description: "Short summary"
      label: "Summary for DB and user"
      required: true
      default: "ex"
      type: "string"  
services:
  mariadb:
    drain_timeout_ms: 200
    scale: 1
    start_on_create: true
  loadbalancer:
    scale: 1
    start_on_create: true
    lb_config:
      certs: []
      port_rules:
      - hostname: www.{Domain}
        priority: 2
        protocol: http
        service: prestashop
        source_port: 80
        target_port: 80
      - hostname: {Domain}
        path: ''
        priority: 3
        protocol: http
        service: prestashop
        source_port: 80
        target_port: 80
    health_check:
      healthy_threshold: 2
      response_timeout: 2000
      port: 42
      unhealthy_threshold: 3
      initializing_timeout: 60000
      interval: 2000
      reinitializing_timeout: 60000
  prestashop:
    drain_timeout_ms: 1800
    scale: 1
    start_on_create: true