version: '2'
services:
  mariadb:
      image: 'mariadb:latest'
      volumes:
        - 'mariadb_data:/mariadb'
      environment:
        - MYSQL_ROOT_PASSWORD=${mariadb_root_password}
        - MYSQL_USER=${db_user}
        - MYSQL_PASSWORD=${db_password}
        - MYSQL_DATABASE=${db_name}
  wordpress:
      image: 'hkosbab/wordpress:latest'
      volumes:
        - 'wordpress_data:/var/www/html/wordpress/wp-content'
        - 'wordpress_conf:/var/www/html/wordpress/'
      depends_on:
        - mariadb
volumes:
  mariadb_data:
    driver: ${volume_driver}
  wordpress_data:
    driver: ${volume_driver}
