version: '2'
services:
  mariadb:
      image: 'mariadb:latest'
      volumes:
        - 'mariadb_data:/mariadb'
      environment:
        - MARIADB_ROOT_PASSWORD=${mariadb_root_password}
        - MARIADB_USER=${mariadb_user}
        - MARIADB_PASSWORD=${mariadb_user_password}
        - MARIADB_DATABASE=${mariadb_database_name}
  wordpress:
      image: 'hkosbab/wordpress:latest'
      volumes:
        - 'wordpress_data:/var/www/html/wordpress/wp-content'
      depends_on:
        - mariadb
volumes:
  mariadb_data:
    driver: ${volume_driver}
  wordpress_data:
    driver: ${volume_driver}
