version: '2'
services:
  mariadb:
      image: 'mariadb:latest'
      volumes:
        - 'mariadb_data:/mariadb'
      environment:
        - MYSQL_ROOT_PASSWORD=${mariadb_root_password}
        - MYSQL_USER=${db_user}
        - MYSQL_PASSWORD=${db_password}
        - MYSQL_DATABASE=${db_name}
  vtiger:
      image: hkosbab/vtiger
      ports:
      - 22280:80
      volumes:
      - vtiger:/var/www/html/
      depends_on:
        - mariadb      
volumes:
  mariadb_data:
    driver: ${volume_driver}
  drupal_data:
    driver: ${volume_driver}
