version: '2'
services:
  mariadb:
      image: 'mariadb:10.3'
      volumes:
        - 'mariadb_data:/mariadb'
      environment:
        - MARIADB_ROOT_PASSWORD=${mariadb_root_password}
        - MARIADB_USER=${mariadb_user}
        - MARIADB_PASSWORD=${mariadb_user_password}
        - MARIADB_DATABASE=${mariadb_database_name}
  vtiger:
      image: ldavid/vtiger7
      ports:
      - 22280:80
      volumes:
      - vtiger:/var/www/html/
      depends_on:
        - mariadb
      environment:
        - DRUPAL_DATABASE_NAME=${mariadb_database_name}
        - DRUPAL_DATABASE_USER=${mariadb_user} 
        - DRUPAL_DATABASE_PASSWORD=${mariadb_user_password}       
        - DRUPAL_USERNAME=${drupal_username}
        - DRUPAL_PASSWORD=${drupal_password}
volumes:
  mariadb_data:
    driver: ${volume_driver}
  drupal_data:
    driver: ${volume_driver}
