version: '2'
services:
  mariadb:
      image: 'mariadb:latest'
      volumes:
        - 'mariadb_data:/mariadb'
      environment:
        - MARIADB_ROOT_PASSWORD=${mariadb_root_password}
        - MARIADB_USER=${db_user}
        - MARIADB_PASSWORD=${db_password}
        - MARIADB_DATABASE=${db_name}
  vtiger:
      image: ldavid/vtiger7
      ports:
      - 22280:80
      volumes:
      - vtiger:/var/www/html/
      depends_on:
        - mariadb
      environment:
        - DB_HOSTNAME=mariadb
        - DB_NAME=${db_name}
        - DB_USERNAME=${db_user} 
        - DB_PASSWORD=${db_password}       
volumes:
  mariadb_data:
    driver: ${volume_driver}
  drupal_data:
    driver: ${volume_driver}
